library(Quandl)
library(TTR,quietly=TRUE)
library(bit,quietly=TRUE)
library(chunked);
library(compiler)
library(data.table);
library(dplyr)
library(dtplyr);
library(DT)
library(ff,quietly=TRUE,warn.conflicts=FALSE)
library(flexdashboard)
library(lubridate);
library(date);
#library(quantmod)
library(readr)
library(stringr)
library(tictoc)
library(tidyquant);
library(tidyselect);
library(tibbletime);
library(xts)
library(rbokeh);
library(dygraphs);
#library(rlist);
#library(pipeR);
library(caTools);
library(qdapTools);
library(pryr);
library(abind);
library(formattable);
library(combinat);
library(htmltools)
enableJIT(3)
#library(pryr);

library(arrayhelpers);
library(PerformanceAnalytics)
library(modelr);
#library(randomForest);
#library(randomForestExplainer);
#library(randomForestSRC);
library(party);
library(ggplot2);
library(gridExtra);
library(arm);
options(java.parameters = "-Xmx6000m")
library(BART);
library(rJava)
library(bartMachine);
library(robustHD);
library(xlsx)
#library(installr)
#check.for.updates.R()
#install.R() 

